[repo]
logging = "warn"


[repo_docs]
enabled = true
docs_root = "docs"
project = "vcr"
name = "NVIDIA VR Capture and Replay (VCR) Documentation"
version = "NVVCRVERSION"
copyright_start = 2023
logo = "${root}/static/nvidia-logo.png"
favicon = "${root}/static/favicon.ico"
social_media_set = ""

[repo_docs.builds.latex]
output_format = "latex"
latex_font_directories.nvidia_sans = "./../../../../fonts/NVIDIASans/"
latex_font_directories.roboto_mono = "./../../../../fonts/Roboto_Mono/static/"


