
name: VCR build

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: "Build ${{ matrix.build_type }} on ${{ matrix.os }}"
    runs-on: ${{matrix.os}}
    
    strategy:
      matrix:
        os: [windows-latest, windows-2019]
        build_type: [Debug, Release]

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Build
      shell: cmd
      run: ${{github.workspace}}\build.cmd
    
    - if: ${{ matrix.build_type == 'Release' }}
      name: Upload Artifacts
      uses: actions/upload-artifact@v4
      with:
        name: VCR-${{matrix.os}}
        path: _out