name: Convert Readme.md to PDF

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: test something
        run: |
          ls
          mkdir _out
          pandoc -o readme1.pdf README.md
          ls
          pandoc -o _out/readme1.pdf README.md      
          ls 
          ls _out
      - name: Pandoc conversion
        uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t pdf -o readme.pdf README.md
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: readme.pdf
          path: ./readme.pdf
