name: Convert Readme.md to PDF

on:
  workflow_dispatch:

jobs:
  convert_via_pandoc:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4
      - uses: docker://pandoc/latex:2.9
        with:
          args: -f markdown -t pdf -o readme.pdf README.md
      - uses: actions/upload-artifact@v4
        with:
          name: readme
          path: readme
